version: '3.3'
services:

  grafana:
    links:
      - db:db
    image: grafana/grafana-enterprise
    volumes:
      - ./grafana:/var/lib/grafana:rw
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_DATABASE_HOST=db:3306
      - GF_DATABASE_NAME=testdb
      - GF_DATABASE_USER=user
      - GF_DATABASE_PASSWORD=password
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_MAX_OPEN_CONN=300
    ports:
      - "3000:3000"
    depends_on: [ "db" ]


  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'testdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql


volumes:
  my-db: