apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    create database if not exists testdb;
    use testdb;
    create table cpu(uuid varchar(100) primary key, hostname text, model text, utilization float, time timestamp);
    create table memory(uuid varchar(100) not null primary key, hostname text, total float, utilization float, time timestamp);
    create table system(uuid varchar(100) primary key, hostname text, ip text, os text, architecture text, platform text, version text,online_users int, latency int, time timestamp);    
    create table tcp(uuid varchar(100) primary key, hostname text, queue_size int, segments_received int, segments_sent int, time timestamp);